
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Aprendices
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Aprendices()
    {

        this.Asignar_Fase = new HashSet<Asignar_Fase>();

        this.Bitacora_Aprendiz = new HashSet<Bitacora_Aprendiz>();

        this.Grupo_Aprendices = new HashSet<Grupo_Aprendices>();

    }


    public int id_aprendiz { get; set; }

    public Nullable<System.DateTime> inicio_contrato { get; set; }

    public Nullable<System.DateTime> fin_contrato { get; set; }

    public Nullable<int> id_contrato { get; set; }

    public string descripcion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Asignar_Fase> Asignar_Fase { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Bitacora_Aprendiz> Bitacora_Aprendiz { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Grupo_Aprendices> Grupo_Aprendices { get; set; }

    public virtual Personas Personas { get; set; }

    public virtual Tipo_Contrato Tipo_Contrato { get; set; }

}

}
