
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Asignar_Fase
{

    public int id { get; set; }

    public Nullable<int> id_aprendiz { get; set; }

    public Nullable<int> id_fase_ciclo { get; set; }

    public Nullable<int> id_estado { get; set; }

    public Nullable<System.DateTime> fecha_asignacion { get; set; }

    public string descripcion { get; set; }



    public virtual Aprendices Aprendices { get; set; }

    public virtual Estado_asignacion Estado_asignacion { get; set; }

    public virtual Fases_de_Ciclos Fases_de_Ciclos { get; set; }

}

}
