
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Bitacora_Aprendiz
{

    public int id { get; set; }

    public Nullable<int> id_aprendiz { get; set; }

    public Nullable<int> id_bitacora { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public string archivo { get; set; }

    public string descripcion { get; set; }



    public virtual Aprendices Aprendices { get; set; }

    public virtual Bitacoras Bitacoras { get; set; }

}

}
