
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ciclos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ciclos()
    {

        this.Fases_de_Ciclos = new HashSet<Fases_de_Ciclos>();

    }


    public int id_ciclo { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> id_estado { get; set; }



    public virtual Estados_Ciclos Estados_Ciclos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Fases_de_Ciclos> Fases_de_Ciclos { get; set; }

}

}
