
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cliente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cliente()
    {

        this.Solicitud = new HashSet<Solicitud>();

    }


    public int id_cliente { get; set; }

    public string nombre { get; set; }

    public string email { get; set; }

    public string numero_contacto { get; set; }

    public Nullable<int> id_documento { get; set; }

    public Nullable<int> tipo_cliente { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Solicitud> Solicitud { get; set; }

    public virtual Tipo_Cliente Tipo_Cliente1 { get; set; }

    public virtual Documento Documento { get; set; }

}

}
