

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FabricaSoftwareEntities : DbContext
{
    public FabricaSoftwareEntities()
        : base("name=FabricaSoftwareEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Adquirir_Servicios> Adquirir_Servicios { get; set; }

    public virtual DbSet<Agenda> Agenda { get; set; }

    public virtual DbSet<Aprendices> Aprendices { get; set; }

    public virtual DbSet<Asesores> Asesores { get; set; }

    public virtual DbSet<Asignar_Fase> Asignar_Fase { get; set; }

    public virtual DbSet<Bitacora_Aprendiz> Bitacora_Aprendiz { get; set; }

    public virtual DbSet<Bitacora_Asesor> Bitacora_Asesor { get; set; }

    public virtual DbSet<Bitacoras> Bitacoras { get; set; }

    public virtual DbSet<Ciclos> Ciclos { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Como_Lo_Hacemos> Como_Lo_Hacemos { get; set; }

    public virtual DbSet<Documento> Documento { get; set; }

    public virtual DbSet<Estado_asignacion> Estado_asignacion { get; set; }

    public virtual DbSet<Estado_Proyecto> Estado_Proyecto { get; set; }

    public virtual DbSet<Estado_Solicitud> Estado_Solicitud { get; set; }

    public virtual DbSet<Estado_Viabilidad> Estado_Viabilidad { get; set; }

    public virtual DbSet<EstadoAgenda> EstadoAgenda { get; set; }

    public virtual DbSet<Estados> Estados { get; set; }

    public virtual DbSet<Estados_Ciclos> Estados_Ciclos { get; set; }

    public virtual DbSet<Estados_Fases> Estados_Fases { get; set; }

    public virtual DbSet<Fases> Fases { get; set; }

    public virtual DbSet<Fases_de_Ciclos> Fases_de_Ciclos { get; set; }

    public virtual DbSet<Grupo_Aprendices> Grupo_Aprendices { get; set; }

    public virtual DbSet<Grupos> Grupos { get; set; }

    public virtual DbSet<Imagenes> Imagenes { get; set; }

    public virtual DbSet<Modulos> Modulos { get; set; }

    public virtual DbSet<Nuestros_Servicios> Nuestros_Servicios { get; set; }

    public virtual DbSet<Operaciones> Operaciones { get; set; }

    public virtual DbSet<Personas> Personas { get; set; }

    public virtual DbSet<pqrs> pqrs { get; set; }

    public virtual DbSet<Proyecto> Proyecto { get; set; }

    public virtual DbSet<Quienes_Somos> Quienes_Somos { get; set; }

    public virtual DbSet<Rol_Operaciones> Rol_Operaciones { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Sexo> Sexo { get; set; }

    public virtual DbSet<Solicitud> Solicitud { get; set; }

    public virtual DbSet<Tipo_Cliente> Tipo_Cliente { get; set; }

    public virtual DbSet<Tipo_Contrato> Tipo_Contrato { get; set; }

    public virtual DbSet<Tipo_Documento> Tipo_Documento { get; set; }

    public virtual DbSet<Tipo_Imagen> Tipo_Imagen { get; set; }

    public virtual DbSet<Tipo_Solicitante> Tipo_Solicitante { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    public virtual DbSet<LogAgenda> LogAgenda { get; set; }

    public virtual DbSet<historialGrupos> historialGrupos { get; set; }

}

}

