
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class historialGrupos
{

    public int id { get; set; }

    public string rolUsuario { get; set; }

    public string nombreUsuario { get; set; }

    public string CorreoUsuario { get; set; }

    public Nullable<int> idUsuario { get; set; }

    public string accion { get; set; }

    public Nullable<int> idResponsable { get; set; }

    public Nullable<System.DateTime> fechaAccion { get; set; }

    public Nullable<int> idGrupo { get; set; }

}

}
