
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Imagenes
{

    public int idImage { get; set; }

    public Nullable<int> idTipo { get; set; }

    public string imageUrl { get; set; }

    public string nombreUsuario { get; set; }



    public virtual Tipo_Imagen Tipo_Imagen { get; set; }

}

}
