
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LogAgenda
{

    public int id { get; set; }

    public int idAgenda { get; set; }

    public string fechaAgenda { get; set; }

    public string Horario { get; set; }

    public string descripcion { get; set; }

    public int ResponsableAgenda { get; set; }

    public int ProyectoAgenda { get; set; }

    public int clienteAgenda { get; set; }

    public string asistentes { get; set; }

    public int estadoAgenda { get; set; }

    public int grupoAgenda { get; set; }

    public string idResponsable { get; set; }

    public Nullable<System.DateTime> fechaLog { get; set; }

    public string Asunto { get; set; }

}

}
