
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Personas
{

    public int documento { get; set; }

    public string nombres { get; set; }

    public string apellidos { get; set; }

    public string email { get; set; }

    public Nullable<System.DateTime> fecha_nacimiento { get; set; }

    public string numero_contacto { get; set; }

    public Nullable<int> id_documento { get; set; }

    public Nullable<int> id_sexo { get; set; }



    public virtual Aprendices Aprendices { get; set; }

    public virtual Asesores Asesores { get; set; }

    public virtual Sexo Sexo { get; set; }

    public virtual Tipo_Documento Tipo_Documento { get; set; }

}

}
