
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Proyecto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Proyecto()
    {

        this.Agenda = new HashSet<Agenda>();

    }


    public int id_proyecto { get; set; }

    public Nullable<System.DateTime> fecha_inicio { get; set; }

    public Nullable<System.DateTime> fecha_terminación { get; set; }

    public string alcance { get; set; }

    public string archivo { get; set; }

    public Nullable<int> id_estado { get; set; }

    public Nullable<int> id_bitacora { get; set; }

    public Nullable<int> id_grupo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Agenda> Agenda { get; set; }

    public virtual Bitacoras Bitacoras { get; set; }

    public virtual Estado_Proyecto Estado_Proyecto { get; set; }

    public virtual Grupos Grupos { get; set; }

    public virtual Solicitud Solicitud { get; set; }

}

}
