
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Solicitud
{

    public int id_solicitud { get; set; }

    public Nullable<int> id_cliente { get; set; }

    public Nullable<int> id_tipoCliente { get; set; }

    public string tipo_avance { get; set; }

    public string archivo_adjunto { get; set; }

    public string nombre_solicitante { get; set; }

    public string nombre_empresa { get; set; }

    public string contraprestacion { get; set; }

    public Nullable<System.DateTime> fecha_solicitud { get; set; }

    public int tiempo_estimado { get; set; }

    public string tema_proyecto { get; set; }

    public int grupo_afectado { get; set; }

    public string descripcion { get; set; }

    public string area { get; set; }

    public Nullable<int> id_viabilidad { get; set; }

    public Nullable<int> costo_real { get; set; }

    public string descripcion_costo { get; set; }

    public Nullable<int> id_estado_solicitud { get; set; }

    public string com_admin { get; set; }



    public virtual Cliente Cliente { get; set; }

    public virtual Estado_Solicitud Estado_Solicitud { get; set; }

    public virtual Estado_Viabilidad Estado_Viabilidad { get; set; }

    public virtual Proyecto Proyecto { get; set; }

    public virtual Tipo_Solicitante Tipo_Solicitante { get; set; }

}

}
