
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SoftwareFactory.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Usuarios
{

    public int id_usuario { get; set; }

    public string email { get; set; }

    public string hash_password { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<int> id_rol { get; set; }

    public Nullable<int> id_estado { get; set; }



    public virtual Estados Estados { get; set; }

    public virtual Roles Roles { get; set; }

}

}
